# YOLOv5-Face (face_detection default)
model_path: ~/.cache/models/vision/yolov5-face/yolov5n-face_cut.q.onnx
test_image: ~/.cache/assets/image/006_test.jpg
class: deploy.yolov5_face.YOLOv5FaceDetector
default_params:
  conf_thres: 0.25
  iou_thres: 0.45
  conf_threshold: 0.25
  iou_threshold: 0.45
  num_threads: 4
  providers:
    - SpaceMITExecutionProvider
